language: python
python:
  - "2.6"
  - "2.7"
matrix:
    allow_failures:
        - python: "2.6"
install:
- sudo apt-get update -qq
- sudo apt-get install -qq python-epydoc
- "pip install -r requirements/test.txt --use-mirrors"
script: sh run_tests.sh
