language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
  # TODO: http://www.topbug.net/blog/2012/05/27/use-travis-ci-with-jython/
  # TODO: Can I use Travis's OSX worker without paying for Pro?
matrix:
    allow_failures:
        - python: "3.2"
        - python: "3.3"
install:
- sudo apt-get update -qq
- sudo apt-get install -qq python-epydoc python-docutils --no-install-recommends
- pip install -r requirements/test.txt --use-mirrors
- pip install coveralls --use-mirrors
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -r requirements/pre_py27.txt --use-mirrors; fi
script: ./run_tests.py
after_success: coveralls
