language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "pypy"
  # TODO: Get the test system imports working in Python 3.x and test it.
matrix:
    allow_failures:
        - python: "2.5"
        - python: "pypy"
install:
- sudo apt-get update -qq
- sudo apt-get install -qq python-epydoc
- "pip install -r requirements/test.txt --use-mirrors"
- if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install --use-mirrors ordereddict unittest2; fi
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors ordereddict unittest2; fi
script: ./run_tests.py
